# Generated by Django 4.2.7 on 2023-11-28 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeBarang', models.CharField(max_length=20, unique=True)),
                ('NamaBarang', models.CharField(max_length=100)),
                ('Satuan', models.CharField(max_length=20)),
                ('HargaSatuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeKasir', models.CharField(max_length=20, unique=True)),
                ('Nama', models.CharField(max_length=100)),
                ('HP', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeTenan', models.CharField(max_length=20, unique=True)),
                ('NamaTenan', models.CharField(max_length=100)),
                ('HP', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeNota', models.CharField(max_length=20, unique=True)),
                ('TglNota', models.DateField()),
                ('JamNota', models.TimeField()),
                ('JumlahBelanja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Diskon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KodeKasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi_pujasera.kasir')),
                ('KodeTenan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi_pujasera.tenan')),
            ],
        ),
        migrations.CreateModel(
            name='BarangNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JumlahBarang', models.PositiveIntegerField()),
                ('HargaSatuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KodeBarang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi_pujasera.barang')),
                ('KodeNota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi_pujasera.nota')),
            ],
        ),
    ]
